### ISSUE TITLE
Setting autoPlay to false but defining an onPlay callback tints the console yellow

### ISSUE THREAD

**Issue by GGGuenni** [gskinner/flutter_animate#132] opened 2024-02-28 12:35 UTC
## Problem: 
Running the flutter project below results in a yellow tinted console. Wouln't be a problem if it wouldn't also block Android Studio from both hot restarting and hot reloading.
I've only run the project on an Android device but I don't think that it makes a difference

![image](https://github.com/gskinner/flutter_animate/assets/24532072/17537814-e0cb-40dc-9b75-90a9d8928b79)

## Steps to reproduce:

Simply run the following project:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const Placeholder().animate(
        autoPlay: false,
        onPlay: (controller) => controller.repeat(),
      ),
    );
  }
}
```

**Comment by Junesui** [comment] 2024-08-23 10:50
same issue.

**Comment by gskinner** [comment] 2024-08-27 17:35
Thanks for the report. I was missing a formatting reset code. It looks like VSCode automatically resets after each print (which is why I didn't catch this), but Android Studio apparently does not.

Should be resolved in: 491f3d1c1b4daea28c94b3ff08271738161975d4 Testing is appreciated.

Really odd that text formatting in the console would cause issues with hot reloading though. That sounds like an Android Studio bug, if true.

**Closed by gskinner** 2024-08-27 17:35 UTC
Labels: bug

**Comment by Nico04** [comment] 2024-10-17 08:37
I have this issue too, but last version doesn't seems to contains this fix, is this normal ?

**Comment by Nico04** [comment] 2024-11-11 16:16
I can confirm the commit fixes the issue, but unfortunately no pub.dev release contains it.
