### ISSUE TITLE
Control the animation when the widget removes from the screen

### ISSUE THREAD

**Issue by elio1fiore** [gskinner/flutter_animate#97] opened 2023-07-06 23:29 UTC
Hello lads. I can't figure out how I can make an animation when the widget is deleted from the screen. That is from the widget tree. For example I put an if in a Column and when the widget is removed I would like to make an animation.

Thank you very much for those who will explain to me

**Comment by gskinner** [comment] 2023-07-25 21:09
Duplicate of #29

**Closed by gskinner** 2023-07-25 21:09 UTC
Labels: duplicate
