### ISSUE TITLE
Export the example for web and provide link in README

### ISSUE THREAD

**Issue by fisforfaheem** [gskinner/flutter_animate#133] opened 2024-03-12 12:23 UTC
there are so many stuff, but most of us dont now how to use or exploring examples is too difficult.

Kindly do some work on this.

**Comment by gskinner** [comment] 2024-08-27 17:55
The included example file has a page showing a simple demo of every single effect included with Animate (hopefully I haven't missed any!).

I don't think I'm going to introduce the maintenance burden of maintaining gifs, or bloat the README with this, but perhaps I could export that page to web at some point and include a link to it. I'll rename this request and keep it open to track.

Feedback welcome.

**Comment by fisforfaheem** [comment] 2024-08-27 19:27
Thanks A demo would be much better a link to a simple Demo website, where user can copy code and easily use that animation in their own projects

**Comment by gskinner** [comment] 2024-08-27 20:00
Just realized this is now a duplicate of #84

**Closed by gskinner** 2024-08-27 20:00 UTC
Labels: documentation, duplicate
